version: '3.7'

services:
  mysql:
    image: mysql:8
    volumes:
      -db:/var/lib/mysql
    ports:
      -3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=igor-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root

api:
  build:
    context: .
  ports:
    - 3001:3000
  depends_on:
    - mysql
  networks:
    - networkapinode-network

networks:
  networkapinode-network:
    driver: bridge

volumes:
  db: